export const Skill_data = [
    {
      skill_name: "Html 5",
      Image: "/html.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Css",
      Image: "/css.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Java Script",
      Image: "/js.png",
      width: 65,
      height: 65,
    },
    {
      skill_name: "Tailwind Css",
      Image: "/tailwind.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "React",
      Image: "/react.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Redux",
      Image: "/redux.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "React Query",
      Image: "/reactquery.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Type Script",
      Image: "/ts.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Next js 13",
      Image: "/next.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Framer Motion",
      Image: "/framer.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Stripe Payment",
      Image: "/stripe.webp",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Node js",
      Image: "/node-js.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Mongo db",
      Image: "/mongodb.png",
      width: 40,
      height: 40,
    },
  
  ];
  
  
  
  export const Frontend_skill = [
    {
      skill_name: "Html 5",
      Image: "/html.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Css",
      Image: "/css.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Java Script",
      Image: "/js.png",
      width: 65,
      height: 65,
    },
    {
      skill_name: "Tailwind Css",
      Image: "/tailwind.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Material UI",
      Image: "/mui.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "React",
      Image: "/react.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Redux",
      Image: "/redux.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "React Query",
      Image: "/reactquery.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Type Script",
      Image: "/ts.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Next js 13",
      Image: "/next.png",
      width: 80,
      height: 80,
    },
  ];
  
  export const Backend_skill = [
    {
      skill_name: "Node js",
      Image: "/node-js.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Express js",
      Image: "/express.png",
      width: 80,
      height: 80,
    },
    {
      skill_name: "Mongo db",
      Image: "/mongodb.png",
      width: 40,
      height: 40,
    },
    {
      skill_name: "Fire base",
      Image: "/Firebase.png",
      width: 55,
      height: 55,
    },
    {
      skill_name: "Postger SQL",
      Image: "/postger.png",
      width: 70,
      height: 70,
    },
    {
      skill_name: "My SQL",
      Image: "/mysql.png",
      width: 70,
      height: 70,
    },
    {
      skill_name: "Prisma",
      Image: "/prisma.webp",
      width: 70,
      height: 70,
    },
    {
      skill_name: "Graphql",
      Image: "/graphql.png",
      width: 80,
      height: 80,
    },
  ];
  
  export const Full_stack = [
    {
      skill_name: "React Native",
      Image: "/ReactNative .png",
      width: 70,
      height: 70,
    },
    {
      skill_name: "Tauri",
      Image: "/tauri.svg",
      width: 70,
      height: 70,
    },
    {
      skill_name: "Docker",
      Image: "/docker.webp",
      width: 70,
      height: 70,
    },
  
    {
      skill_name: "Figma",
      Image: "/figma.png",
      width: 50,
      height: 50,
    },
  
  ];

  export const projects = [
    {
      src: "/img/csgo.png",
      title: "CSFairTrade",
      description: "A full-stack trading platform providing a secure and user friendly environment for trading in-game skins in the CS:GO market.",
      sourceUrl: "https://csfairtrade-frontend.vercel.app/",
      youtubeUrl: "https://www.youtube.com/watch?v=fYdAn0O2g0Q",
      githubUrl: null,
      startDate: "2021-12-25",
      endDate: "2023-06-01",
      technologyStack: [
        "React.js",
        "Node.js",
        "Express.js",
        "MySQL",
        "Socket.io",
        "HTTPS",
        "Nginx",
        "Digital Ocean",
        "Azure",
        "Jest",
        "Postman",
        "Steam Modules",
        "Sequelize",
        "Linux (Ubuntu)",
        "Event-Driven",
        "Github",
        "Github Actions",
      ],
    },
    {
      src: "/img/codemate.png",
      title: "CodeMate",
      description: "A dynamic platform designed to enhance collaboration among students in the tech field, facilitating the sharing of ideas, project development, and networking opportunities.",
      sourceUrl: "https://codecomrades.vercel.app/",
      youtubeUrl: null,
      githubUrl: null,
      startDate: "2021-12-25",
      endDate: "2023-06-01",
      technologyStack: [
        "React.js",
        "Node.js",
        "Express.js",
        "MySQL",
        "Socket.io",
        "HTTPS",
        "Nginx",
        "Digital Ocean",
        "Azure",
        "Jest",
        "Postman",
        "Steam Modules",
        "Sequelize",
        "Linux (Ubuntu)",
        "Event-Driven",
        "Github",
        "Github Actions",
      ],
    },
    {
      src: "/img/snipeskins.jpg",
      title: "SnipeSkins",
      description: "A comprehensive trading platform designed for Rust in-game skins. SnipeSkins aims to provide a seamless experience for trading digital assets.",
      sourceUrl: "https://snipeskins.com/",
      youtubeUrl: null,
      githubUrl: null,
      startDate: "2021-12-25",
      endDate: "2023-06-01",
      technologyStack: [
        "React.js",
        "Node.js",
        "Express.js",
        "MySQL",
        "Socket.io",
        "HTTPS",
        "Nginx",
        "Digital Ocean",
        "Azure",
        "Jest",
        "Postman",
        "Steam Modules",
        "Sequelize",
        "Linux (Ubuntu)",
        "Event-Driven",
        "Github",
        "Github Actions",
      ],
    },
    {
      src: "/img/queue-student.png",
      title: "Distributed Queue System For Students",
      description: "Developed an Event-driven queue system for students and supervisors with ZeroMQ, Spring Boot, and Python.",
      sourceUrl: "https://www.youtube.com/watch?v=m-omLSKbUtc",
      githubUrl: "https://github.com/RaymondSWE/Queue-system---Event-Driven-Architecture",
      youtubeUrl: "https://www.youtube.com/watch?v=m-omLSKbUtc",
      startDate: "2021-12-25",
      endDate: "2023-06-01",
      technologyStack: [
        "React.js",
        "Node.js",
        "Express.js",
        "MySQL",
        "Socket.io",
        "HTTPS",
        "Nginx",
        "Digital Ocean",
        "Azure",
        "Jest",
        "Postman",
        "Steam Modules",
        "Sequelize",
        "Linux (Ubuntu)",
        "Event-Driven",
        "Github",
        "Github Actions",
      ],
    },
    {
      src: "/img/massageapp.png",
      title: "Booking Application For Company Employees",
      description: "Developed an appointment management system for Bally's employees, providing a system for their daily massage appointments.",
      sourceUrl: "https://massage.silverspin.com/",
      youtubeUrl: null,
      githubUrl: null,
      startDate: "2021-12-25",
      endDate: "2023-06-01",
      technologyStack: [
        "React.js",
        "Node.js",
        "Express.js",
        "MySQL",
        "Socket.io",
        "HTTPS",
        "Nginx",
        "Digital Ocean",
        "Azure",
        "Jest",
        "Postman",
        "Steam Modules",
        "Sequelize",
        "Linux (Ubuntu)",
        "Event-Driven",
        "Github",
        "Github Actions",
      ],
    },
    {
      src: "/img/blackjack.png",
      title: "Blackjack Game",
      description: "A desktop version of the Blackjack card game, developed to transform the game rules into logic and implement it in Java.",
      sourceUrl: null,
      youtubeUrl: null,
      githubUrl: null,
      startDate: "2021-12-25",
      endDate: "2023-06-01",
      technologyStack: [
        "React.js",
        "Node.js",
        "Express.js",
        "MySQL",
        "Socket.io",
        "HTTPS",
        "Nginx",
        "Digital Ocean",
        "Azure",
        "Jest",
        "Postman",
        "Steam Modules",
        "Sequelize",
        "Linux (Ubuntu)",
        "Event-Driven",
        "Github",
        "Github Actions",
      ],
    },
    {
      src: "/img/webportfolio.png",
      title: "Web Portfolio",
      description: "My personal web portfolio, designed to be a comprehensive showcase of my skills, experiences, and projects.",
      sourceUrl: null,
      youtubeUrl: null,
      githubUrl: null,
      startDate: "2021-12-25",
      endDate: "2023-06-01",
      technologyStack: [
        "React.js",
        "Node.js",
        "Express.js",
        "MySQL",
        "Socket.io",
        "HTTPS",
        "Nginx",
        "Digital Ocean",
        "Azure",
        "Jest",
        "Postman",
        "Steam Modules",
        "Sequelize",
        "Linux (Ubuntu)",
        "Event-Driven",
        "Github",
        "Github Actions",
      ],
    },
    {
      src: "/img/RayDeploy.png",
      title: "Simple Website",
      description: "The project was developed while following a YouTube tutorial to grasp the fundamentals of web development.",
      sourceUrl: null,
      youtubeUrl: null,
      githubUrl: null,
      startDate: "2021-12-25",
      endDate: "2023-06-01",
      technologyStack: [
        "React.js",
        "Node.js",
        "Express.js",
        "MySQL",
        "Socket.io",
        "HTTPS",
        "Nginx",
        "Digital Ocean",
        "Azure",
        "Jest",
        "Postman",
        "Steam Modules",
        "Sequelize",
        "Linux (Ubuntu)",
        "Event-Driven",
        "Github",
        "Github Actions",
      ],
    }
  ];
  
  
  
  
  export const Other_skill = [
    {
      skill_name: "Go",
      Image: "/go.png",
      width: 60,
      height: 60,
    },
  ];


  
  
  
  
  